<?php

/**
 * Invoice
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mustangserver
 *
 * Mustangproject e-invoice REST server API
 *
 * OpenAPI spec version: v0.7.0
 * Contact: jstaerk@usegroup.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.38
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Invoice Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Invoice implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'Invoice';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'document_name' => 'string',
        'document_code' => 'string',
        'number' => 'string',
        'own_organisation_full_plaintext_info' => 'string',
        'reference_number' => 'string',
        'ship_to_organisation_id' => 'string',
        'ship_to_organisation_name' => 'string',
        'ship_to_street' => 'string',
        'ship_to_zip' => 'string',
        'ship_to_location' => 'string',
        'ship_to_country' => 'string',
        'buyer_order_referenced_document_id' => 'string',
        'invoice_referenced_document_id' => 'string',
        'buyer_order_referenced_document_issue_date_time' => 'string',
        'own_foreign_organisation_id' => 'string',
        'own_organisation_name' => 'string',
        'currency' => 'string',
        'payment_term_description' => 'string',
        'issue_date' => '\DateTime',
        'due_date' => '\DateTime',
        'delivery_date' => '\DateTime',
        'total_prepaid_amount' => 'float',
        'sender' => '\Swagger\Client\Model\IZUGFeRDExportableTradeParty',
        'recipient' => '\Swagger\Client\Model\IZUGFeRDExportableTradeParty',
        'delivery_address' => '\Swagger\Client\Model\TradeParty',
        'notes' => 'string[]',
        'seller_order_referenced_document_id' => 'string',
        'contract_referenced_document' => 'string',
        'payment_terms' => '\Swagger\Client\Model\IZUGFeRDPaymentTerms',
        'invoice_referenced_issue_date' => '\DateTime',
        'specified_procuring_project_id' => 'string',
        'specified_procuring_project_name' => 'string',
        'despatch_advice_referenced_document_id' => 'string',
        'valid' => 'bool',
        'zfallowances' => '\Swagger\Client\Model\IZUGFeRDAllowanceCharge[]',
        'zfcharges' => '\Swagger\Client\Model\IZUGFeRDAllowanceCharge[]',
        'zflogistics_service_charges' => '\Swagger\Client\Model\IZUGFeRDAllowanceCharge[]',
        'zfitems' => '\Swagger\Client\Model\IZUGFeRDExportableItem[]',
        'trade_settlement' => '\Swagger\Client\Model\IZUGFeRDTradeSettlement[]',
        'own_tax_id' => 'string',
        'own_vatid' => 'string',
        'own_street' => 'string',
        'own_zip' => 'string',
        'own_location' => 'string',
        'own_country' => 'string',
        'detailed_delivery_period_from' => '\DateTime',
        'detailed_delivery_period_to' => '\DateTime',
        'additional_referenced_documents' => '\Swagger\Client\Model\FileAttachment[]',
        'correction' => '\Swagger\Client\Model\Invoice',
        'own_contact' => '\Swagger\Client\Model\Invoice',
        'subject_note' => 'string',
        'trade_settlement_payment' => '\Swagger\Client\Model\IZUGFeRDTradeSettlementPayment[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'document_name' => null,
        'document_code' => null,
        'number' => null,
        'own_organisation_full_plaintext_info' => null,
        'reference_number' => null,
        'ship_to_organisation_id' => null,
        'ship_to_organisation_name' => null,
        'ship_to_street' => null,
        'ship_to_zip' => null,
        'ship_to_location' => null,
        'ship_to_country' => null,
        'buyer_order_referenced_document_id' => null,
        'invoice_referenced_document_id' => null,
        'buyer_order_referenced_document_issue_date_time' => null,
        'own_foreign_organisation_id' => null,
        'own_organisation_name' => null,
        'currency' => null,
        'payment_term_description' => null,
        'issue_date' => 'date-time',
        'due_date' => 'date-time',
        'delivery_date' => 'date-time',
        'total_prepaid_amount' => null,
        'sender' => null,
        'recipient' => null,
        'delivery_address' => null,
        'notes' => null,
        'seller_order_referenced_document_id' => null,
        'contract_referenced_document' => null,
        'payment_terms' => null,
        'invoice_referenced_issue_date' => 'date-time',
        'specified_procuring_project_id' => null,
        'specified_procuring_project_name' => null,
        'despatch_advice_referenced_document_id' => null,
        'valid' => null,
        'zfallowances' => null,
        'zfcharges' => null,
        'zflogistics_service_charges' => null,
        'zfitems' => null,
        'trade_settlement' => null,
        'own_tax_id' => null,
        'own_vatid' => null,
        'own_street' => null,
        'own_zip' => null,
        'own_location' => null,
        'own_country' => null,
        'detailed_delivery_period_from' => 'date-time',
        'detailed_delivery_period_to' => 'date-time',
        'additional_referenced_documents' => null,
        'correction' => null,
        'own_contact' => null,
        'subject_note' => null,
        'trade_settlement_payment' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'document_name' => 'documentName',
        'document_code' => 'documentCode',
        'number' => 'number',
        'own_organisation_full_plaintext_info' => 'ownOrganisationFullPlaintextInfo',
        'reference_number' => 'referenceNumber',
        'ship_to_organisation_id' => 'shipToOrganisationID',
        'ship_to_organisation_name' => 'shipToOrganisationName',
        'ship_to_street' => 'shipToStreet',
        'ship_to_zip' => 'shipToZIP',
        'ship_to_location' => 'shipToLocation',
        'ship_to_country' => 'shipToCountry',
        'buyer_order_referenced_document_id' => 'buyerOrderReferencedDocumentID',
        'invoice_referenced_document_id' => 'invoiceReferencedDocumentID',
        'buyer_order_referenced_document_issue_date_time' => 'buyerOrderReferencedDocumentIssueDateTime',
        'own_foreign_organisation_id' => 'ownForeignOrganisationID',
        'own_organisation_name' => 'ownOrganisationName',
        'currency' => 'currency',
        'payment_term_description' => 'paymentTermDescription',
        'issue_date' => 'issueDate',
        'due_date' => 'dueDate',
        'delivery_date' => 'deliveryDate',
        'total_prepaid_amount' => 'totalPrepaidAmount',
        'sender' => 'sender',
        'recipient' => 'recipient',
        'delivery_address' => 'deliveryAddress',
        'notes' => 'notes',
        'seller_order_referenced_document_id' => 'sellerOrderReferencedDocumentID',
        'contract_referenced_document' => 'contractReferencedDocument',
        'payment_terms' => 'paymentTerms',
        'invoice_referenced_issue_date' => 'invoiceReferencedIssueDate',
        'specified_procuring_project_id' => 'specifiedProcuringProjectID',
        'specified_procuring_project_name' => 'specifiedProcuringProjectName',
        'despatch_advice_referenced_document_id' => 'despatchAdviceReferencedDocumentID',
        'valid' => 'valid',
        'zfallowances' => 'zfallowances',
        'zfcharges' => 'zfcharges',
        'zflogistics_service_charges' => 'zflogisticsServiceCharges',
        'zfitems' => 'zfitems',
        'trade_settlement' => 'tradeSettlement',
        'own_tax_id' => 'ownTaxID',
        'own_vatid' => 'ownVATID',
        'own_street' => 'ownStreet',
        'own_zip' => 'ownZIP',
        'own_location' => 'ownLocation',
        'own_country' => 'ownCountry',
        'detailed_delivery_period_from' => 'detailedDeliveryPeriodFrom',
        'detailed_delivery_period_to' => 'detailedDeliveryPeriodTo',
        'additional_referenced_documents' => 'additionalReferencedDocuments',
        'correction' => 'correction',
        'own_contact' => 'ownContact',
        'subject_note' => 'subjectNote',
        'trade_settlement_payment' => 'tradeSettlementPayment'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'document_name' => 'setDocumentName',
        'document_code' => 'setDocumentCode',
        'number' => 'setNumber',
        'own_organisation_full_plaintext_info' => 'setOwnOrganisationFullPlaintextInfo',
        'reference_number' => 'setReferenceNumber',
        'ship_to_organisation_id' => 'setShipToOrganisationId',
        'ship_to_organisation_name' => 'setShipToOrganisationName',
        'ship_to_street' => 'setShipToStreet',
        'ship_to_zip' => 'setShipToZip',
        'ship_to_location' => 'setShipToLocation',
        'ship_to_country' => 'setShipToCountry',
        'buyer_order_referenced_document_id' => 'setBuyerOrderReferencedDocumentId',
        'invoice_referenced_document_id' => 'setInvoiceReferencedDocumentId',
        'buyer_order_referenced_document_issue_date_time' => 'setBuyerOrderReferencedDocumentIssueDateTime',
        'own_foreign_organisation_id' => 'setOwnForeignOrganisationId',
        'own_organisation_name' => 'setOwnOrganisationName',
        'currency' => 'setCurrency',
        'payment_term_description' => 'setPaymentTermDescription',
        'issue_date' => 'setIssueDate',
        'due_date' => 'setDueDate',
        'delivery_date' => 'setDeliveryDate',
        'total_prepaid_amount' => 'setTotalPrepaidAmount',
        'sender' => 'setSender',
        'recipient' => 'setRecipient',
        'delivery_address' => 'setDeliveryAddress',
        'notes' => 'setNotes',
        'seller_order_referenced_document_id' => 'setSellerOrderReferencedDocumentId',
        'contract_referenced_document' => 'setContractReferencedDocument',
        'payment_terms' => 'setPaymentTerms',
        'invoice_referenced_issue_date' => 'setInvoiceReferencedIssueDate',
        'specified_procuring_project_id' => 'setSpecifiedProcuringProjectId',
        'specified_procuring_project_name' => 'setSpecifiedProcuringProjectName',
        'despatch_advice_referenced_document_id' => 'setDespatchAdviceReferencedDocumentId',
        'valid' => 'setValid',
        'zfallowances' => 'setZfallowances',
        'zfcharges' => 'setZfcharges',
        'zflogistics_service_charges' => 'setZflogisticsServiceCharges',
        'zfitems' => 'setZfitems',
        'trade_settlement' => 'setTradeSettlement',
        'own_tax_id' => 'setOwnTaxId',
        'own_vatid' => 'setOwnVatid',
        'own_street' => 'setOwnStreet',
        'own_zip' => 'setOwnZip',
        'own_location' => 'setOwnLocation',
        'own_country' => 'setOwnCountry',
        'detailed_delivery_period_from' => 'setDetailedDeliveryPeriodFrom',
        'detailed_delivery_period_to' => 'setDetailedDeliveryPeriodTo',
        'additional_referenced_documents' => 'setAdditionalReferencedDocuments',
        'correction' => 'setCorrection',
        'own_contact' => 'setOwnContact',
        'subject_note' => 'setSubjectNote',
        'trade_settlement_payment' => 'setTradeSettlementPayment'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'document_name' => 'getDocumentName',
        'document_code' => 'getDocumentCode',
        'number' => 'getNumber',
        'own_organisation_full_plaintext_info' => 'getOwnOrganisationFullPlaintextInfo',
        'reference_number' => 'getReferenceNumber',
        'ship_to_organisation_id' => 'getShipToOrganisationId',
        'ship_to_organisation_name' => 'getShipToOrganisationName',
        'ship_to_street' => 'getShipToStreet',
        'ship_to_zip' => 'getShipToZip',
        'ship_to_location' => 'getShipToLocation',
        'ship_to_country' => 'getShipToCountry',
        'buyer_order_referenced_document_id' => 'getBuyerOrderReferencedDocumentId',
        'invoice_referenced_document_id' => 'getInvoiceReferencedDocumentId',
        'buyer_order_referenced_document_issue_date_time' => 'getBuyerOrderReferencedDocumentIssueDateTime',
        'own_foreign_organisation_id' => 'getOwnForeignOrganisationId',
        'own_organisation_name' => 'getOwnOrganisationName',
        'currency' => 'getCurrency',
        'payment_term_description' => 'getPaymentTermDescription',
        'issue_date' => 'getIssueDate',
        'due_date' => 'getDueDate',
        'delivery_date' => 'getDeliveryDate',
        'total_prepaid_amount' => 'getTotalPrepaidAmount',
        'sender' => 'getSender',
        'recipient' => 'getRecipient',
        'delivery_address' => 'getDeliveryAddress',
        'notes' => 'getNotes',
        'seller_order_referenced_document_id' => 'getSellerOrderReferencedDocumentId',
        'contract_referenced_document' => 'getContractReferencedDocument',
        'payment_terms' => 'getPaymentTerms',
        'invoice_referenced_issue_date' => 'getInvoiceReferencedIssueDate',
        'specified_procuring_project_id' => 'getSpecifiedProcuringProjectId',
        'specified_procuring_project_name' => 'getSpecifiedProcuringProjectName',
        'despatch_advice_referenced_document_id' => 'getDespatchAdviceReferencedDocumentId',
        'valid' => 'getValid',
        'zfallowances' => 'getZfallowances',
        'zfcharges' => 'getZfcharges',
        'zflogistics_service_charges' => 'getZflogisticsServiceCharges',
        'zfitems' => 'getZfitems',
        'trade_settlement' => 'getTradeSettlement',
        'own_tax_id' => 'getOwnTaxId',
        'own_vatid' => 'getOwnVatid',
        'own_street' => 'getOwnStreet',
        'own_zip' => 'getOwnZip',
        'own_location' => 'getOwnLocation',
        'own_country' => 'getOwnCountry',
        'detailed_delivery_period_from' => 'getDetailedDeliveryPeriodFrom',
        'detailed_delivery_period_to' => 'getDetailedDeliveryPeriodTo',
        'additional_referenced_documents' => 'getAdditionalReferencedDocuments',
        'correction' => 'getCorrection',
        'own_contact' => 'getOwnContact',
        'subject_note' => 'getSubjectNote',
        'trade_settlement_payment' => 'getTradeSettlementPayment'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['document_name'] = isset($data['document_name']) ? $data['document_name'] : null;
        $this->container['document_code'] = isset($data['document_code']) ? $data['document_code'] : null;
        $this->container['number'] = isset($data['number']) ? $data['number'] : null;
        $this->container['own_organisation_full_plaintext_info'] = isset($data['own_organisation_full_plaintext_info']) ? $data['own_organisation_full_plaintext_info'] : null;
        $this->container['reference_number'] = isset($data['reference_number']) ? $data['reference_number'] : null;
        $this->container['ship_to_organisation_id'] = isset($data['ship_to_organisation_id']) ? $data['ship_to_organisation_id'] : null;
        $this->container['ship_to_organisation_name'] = isset($data['ship_to_organisation_name']) ? $data['ship_to_organisation_name'] : null;
        $this->container['ship_to_street'] = isset($data['ship_to_street']) ? $data['ship_to_street'] : null;
        $this->container['ship_to_zip'] = isset($data['ship_to_zip']) ? $data['ship_to_zip'] : null;
        $this->container['ship_to_location'] = isset($data['ship_to_location']) ? $data['ship_to_location'] : null;
        $this->container['ship_to_country'] = isset($data['ship_to_country']) ? $data['ship_to_country'] : null;
        $this->container['buyer_order_referenced_document_id'] = isset($data['buyer_order_referenced_document_id']) ? $data['buyer_order_referenced_document_id'] : null;
        $this->container['invoice_referenced_document_id'] = isset($data['invoice_referenced_document_id']) ? $data['invoice_referenced_document_id'] : null;
        $this->container['buyer_order_referenced_document_issue_date_time'] = isset($data['buyer_order_referenced_document_issue_date_time']) ? $data['buyer_order_referenced_document_issue_date_time'] : null;
        $this->container['own_foreign_organisation_id'] = isset($data['own_foreign_organisation_id']) ? $data['own_foreign_organisation_id'] : null;
        $this->container['own_organisation_name'] = isset($data['own_organisation_name']) ? $data['own_organisation_name'] : null;
        $this->container['currency'] = isset($data['currency']) ? $data['currency'] : null;
        $this->container['payment_term_description'] = isset($data['payment_term_description']) ? $data['payment_term_description'] : null;
        $this->container['issue_date'] = isset($data['issue_date']) ? $data['issue_date'] : null;
        $this->container['due_date'] = isset($data['due_date']) ? $data['due_date'] : null;
        $this->container['delivery_date'] = isset($data['delivery_date']) ? $data['delivery_date'] : null;
        $this->container['total_prepaid_amount'] = isset($data['total_prepaid_amount']) ? $data['total_prepaid_amount'] : null;
        $this->container['sender'] = isset($data['sender']) ? $data['sender'] : null;
        $this->container['recipient'] = isset($data['recipient']) ? $data['recipient'] : null;
        $this->container['delivery_address'] = isset($data['delivery_address']) ? $data['delivery_address'] : null;
        $this->container['notes'] = isset($data['notes']) ? $data['notes'] : null;
        $this->container['seller_order_referenced_document_id'] = isset($data['seller_order_referenced_document_id']) ? $data['seller_order_referenced_document_id'] : null;
        $this->container['contract_referenced_document'] = isset($data['contract_referenced_document']) ? $data['contract_referenced_document'] : null;
        $this->container['payment_terms'] = isset($data['payment_terms']) ? $data['payment_terms'] : null;
        $this->container['invoice_referenced_issue_date'] = isset($data['invoice_referenced_issue_date']) ? $data['invoice_referenced_issue_date'] : null;
        $this->container['specified_procuring_project_id'] = isset($data['specified_procuring_project_id']) ? $data['specified_procuring_project_id'] : null;
        $this->container['specified_procuring_project_name'] = isset($data['specified_procuring_project_name']) ? $data['specified_procuring_project_name'] : null;
        $this->container['despatch_advice_referenced_document_id'] = isset($data['despatch_advice_referenced_document_id']) ? $data['despatch_advice_referenced_document_id'] : null;
        $this->container['valid'] = isset($data['valid']) ? $data['valid'] : null;
        $this->container['zfallowances'] = isset($data['zfallowances']) ? $data['zfallowances'] : null;
        $this->container['zfcharges'] = isset($data['zfcharges']) ? $data['zfcharges'] : null;
        $this->container['zflogistics_service_charges'] = isset($data['zflogistics_service_charges']) ? $data['zflogistics_service_charges'] : null;
        $this->container['zfitems'] = isset($data['zfitems']) ? $data['zfitems'] : null;
        $this->container['trade_settlement'] = isset($data['trade_settlement']) ? $data['trade_settlement'] : null;
        $this->container['own_tax_id'] = isset($data['own_tax_id']) ? $data['own_tax_id'] : null;
        $this->container['own_vatid'] = isset($data['own_vatid']) ? $data['own_vatid'] : null;
        $this->container['own_street'] = isset($data['own_street']) ? $data['own_street'] : null;
        $this->container['own_zip'] = isset($data['own_zip']) ? $data['own_zip'] : null;
        $this->container['own_location'] = isset($data['own_location']) ? $data['own_location'] : null;
        $this->container['own_country'] = isset($data['own_country']) ? $data['own_country'] : null;
        $this->container['detailed_delivery_period_from'] = isset($data['detailed_delivery_period_from']) ? $data['detailed_delivery_period_from'] : null;
        $this->container['detailed_delivery_period_to'] = isset($data['detailed_delivery_period_to']) ? $data['detailed_delivery_period_to'] : null;
        $this->container['additional_referenced_documents'] = isset($data['additional_referenced_documents']) ? $data['additional_referenced_documents'] : null;
        $this->container['correction'] = isset($data['correction']) ? $data['correction'] : null;
        $this->container['own_contact'] = isset($data['own_contact']) ? $data['own_contact'] : null;
        $this->container['subject_note'] = isset($data['subject_note']) ? $data['subject_note'] : null;
        $this->container['trade_settlement_payment'] = isset($data['trade_settlement_payment']) ? $data['trade_settlement_payment'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets document_name
     *
     * @return string
     */
    public function getDocumentName()
    {
        return $this->container['document_name'];
    }

    /**
     * Sets document_name
     *
     * @param string $document_name document_name
     *
     * @return $this
     */
    public function setDocumentName($document_name)
    {
        $this->container['document_name'] = $document_name;

        return $this;
    }

    /**
     * Gets document_code
     *
     * @return string
     */
    public function getDocumentCode()
    {
        return $this->container['document_code'];
    }

    /**
     * Sets document_code
     *
     * @param string $document_code document_code
     *
     * @return $this
     */
    public function setDocumentCode($document_code)
    {
        $this->container['document_code'] = $document_code;

        return $this;
    }

    /**
     * Gets number
     *
     * @return string
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param string $number number
     *
     * @return $this
     */
    public function setNumber($number)
    {
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets own_organisation_full_plaintext_info
     *
     * @return string
     */
    public function getOwnOrganisationFullPlaintextInfo()
    {
        return $this->container['own_organisation_full_plaintext_info'];
    }

    /**
     * Sets own_organisation_full_plaintext_info
     *
     * @param string $own_organisation_full_plaintext_info own_organisation_full_plaintext_info
     *
     * @return $this
     */
    public function setOwnOrganisationFullPlaintextInfo($own_organisation_full_plaintext_info)
    {
        $this->container['own_organisation_full_plaintext_info'] = $own_organisation_full_plaintext_info;

        return $this;
    }

    /**
     * Gets reference_number
     *
     * @return string
     */
    public function getReferenceNumber()
    {
        return $this->container['reference_number'];
    }

    /**
     * Sets reference_number
     *
     * @param string $reference_number reference_number
     *
     * @return $this
     */
    public function setReferenceNumber($reference_number)
    {
        $this->container['reference_number'] = $reference_number;

        return $this;
    }

    /**
     * Gets ship_to_organisation_id
     *
     * @return string
     */
    public function getShipToOrganisationId()
    {
        return $this->container['ship_to_organisation_id'];
    }

    /**
     * Sets ship_to_organisation_id
     *
     * @param string $ship_to_organisation_id ship_to_organisation_id
     *
     * @return $this
     */
    public function setShipToOrganisationId($ship_to_organisation_id)
    {
        $this->container['ship_to_organisation_id'] = $ship_to_organisation_id;

        return $this;
    }

    /**
     * Gets ship_to_organisation_name
     *
     * @return string
     */
    public function getShipToOrganisationName()
    {
        return $this->container['ship_to_organisation_name'];
    }

    /**
     * Sets ship_to_organisation_name
     *
     * @param string $ship_to_organisation_name ship_to_organisation_name
     *
     * @return $this
     */
    public function setShipToOrganisationName($ship_to_organisation_name)
    {
        $this->container['ship_to_organisation_name'] = $ship_to_organisation_name;

        return $this;
    }

    /**
     * Gets ship_to_street
     *
     * @return string
     */
    public function getShipToStreet()
    {
        return $this->container['ship_to_street'];
    }

    /**
     * Sets ship_to_street
     *
     * @param string $ship_to_street ship_to_street
     *
     * @return $this
     */
    public function setShipToStreet($ship_to_street)
    {
        $this->container['ship_to_street'] = $ship_to_street;

        return $this;
    }

    /**
     * Gets ship_to_zip
     *
     * @return string
     */
    public function getShipToZip()
    {
        return $this->container['ship_to_zip'];
    }

    /**
     * Sets ship_to_zip
     *
     * @param string $ship_to_zip ship_to_zip
     *
     * @return $this
     */
    public function setShipToZip($ship_to_zip)
    {
        $this->container['ship_to_zip'] = $ship_to_zip;

        return $this;
    }

    /**
     * Gets ship_to_location
     *
     * @return string
     */
    public function getShipToLocation()
    {
        return $this->container['ship_to_location'];
    }

    /**
     * Sets ship_to_location
     *
     * @param string $ship_to_location ship_to_location
     *
     * @return $this
     */
    public function setShipToLocation($ship_to_location)
    {
        $this->container['ship_to_location'] = $ship_to_location;

        return $this;
    }

    /**
     * Gets ship_to_country
     *
     * @return string
     */
    public function getShipToCountry()
    {
        return $this->container['ship_to_country'];
    }

    /**
     * Sets ship_to_country
     *
     * @param string $ship_to_country ship_to_country
     *
     * @return $this
     */
    public function setShipToCountry($ship_to_country)
    {
        $this->container['ship_to_country'] = $ship_to_country;

        return $this;
    }

    /**
     * Gets buyer_order_referenced_document_id
     *
     * @return string
     */
    public function getBuyerOrderReferencedDocumentId()
    {
        return $this->container['buyer_order_referenced_document_id'];
    }

    /**
     * Sets buyer_order_referenced_document_id
     *
     * @param string $buyer_order_referenced_document_id buyer_order_referenced_document_id
     *
     * @return $this
     */
    public function setBuyerOrderReferencedDocumentId($buyer_order_referenced_document_id)
    {
        $this->container['buyer_order_referenced_document_id'] = $buyer_order_referenced_document_id;

        return $this;
    }

    /**
     * Gets invoice_referenced_document_id
     *
     * @return string
     */
    public function getInvoiceReferencedDocumentId()
    {
        return $this->container['invoice_referenced_document_id'];
    }

    /**
     * Sets invoice_referenced_document_id
     *
     * @param string $invoice_referenced_document_id invoice_referenced_document_id
     *
     * @return $this
     */
    public function setInvoiceReferencedDocumentId($invoice_referenced_document_id)
    {
        $this->container['invoice_referenced_document_id'] = $invoice_referenced_document_id;

        return $this;
    }

    /**
     * Gets buyer_order_referenced_document_issue_date_time
     *
     * @return string
     */
    public function getBuyerOrderReferencedDocumentIssueDateTime()
    {
        return $this->container['buyer_order_referenced_document_issue_date_time'];
    }

    /**
     * Sets buyer_order_referenced_document_issue_date_time
     *
     * @param string $buyer_order_referenced_document_issue_date_time buyer_order_referenced_document_issue_date_time
     *
     * @return $this
     */
    public function setBuyerOrderReferencedDocumentIssueDateTime($buyer_order_referenced_document_issue_date_time)
    {
        $this->container['buyer_order_referenced_document_issue_date_time'] = $buyer_order_referenced_document_issue_date_time;

        return $this;
    }

    /**
     * Gets own_foreign_organisation_id
     *
     * @return string
     */
    public function getOwnForeignOrganisationId()
    {
        return $this->container['own_foreign_organisation_id'];
    }

    /**
     * Sets own_foreign_organisation_id
     *
     * @param string $own_foreign_organisation_id own_foreign_organisation_id
     *
     * @return $this
     */
    public function setOwnForeignOrganisationId($own_foreign_organisation_id)
    {
        $this->container['own_foreign_organisation_id'] = $own_foreign_organisation_id;

        return $this;
    }

    /**
     * Gets own_organisation_name
     *
     * @return string
     */
    public function getOwnOrganisationName()
    {
        return $this->container['own_organisation_name'];
    }

    /**
     * Sets own_organisation_name
     *
     * @param string $own_organisation_name own_organisation_name
     *
     * @return $this
     */
    public function setOwnOrganisationName($own_organisation_name)
    {
        $this->container['own_organisation_name'] = $own_organisation_name;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency currency
     *
     * @return $this
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets payment_term_description
     *
     * @return string
     */
    public function getPaymentTermDescription()
    {
        return $this->container['payment_term_description'];
    }

    /**
     * Sets payment_term_description
     *
     * @param string $payment_term_description payment_term_description
     *
     * @return $this
     */
    public function setPaymentTermDescription($payment_term_description)
    {
        $this->container['payment_term_description'] = $payment_term_description;

        return $this;
    }

    /**
     * Gets issue_date
     *
     * @return \DateTime
     */
    public function getIssueDate()
    {
        return $this->container['issue_date'];
    }

    /**
     * Sets issue_date
     *
     * @param \DateTime $issue_date issue_date
     *
     * @return $this
     */
    public function setIssueDate($issue_date)
    {
        $this->container['issue_date'] = $issue_date;

        return $this;
    }

    /**
     * Gets due_date
     *
     * @return \DateTime
     */
    public function getDueDate()
    {
        return $this->container['due_date'];
    }

    /**
     * Sets due_date
     *
     * @param \DateTime $due_date due_date
     *
     * @return $this
     */
    public function setDueDate($due_date)
    {
        $this->container['due_date'] = $due_date;

        return $this;
    }

    /**
     * Gets delivery_date
     *
     * @return \DateTime
     */
    public function getDeliveryDate()
    {
        return $this->container['delivery_date'];
    }

    /**
     * Sets delivery_date
     *
     * @param \DateTime $delivery_date delivery_date
     *
     * @return $this
     */
    public function setDeliveryDate($delivery_date)
    {
        $this->container['delivery_date'] = $delivery_date;

        return $this;
    }

    /**
     * Gets total_prepaid_amount
     *
     * @return float
     */
    public function getTotalPrepaidAmount()
    {
        return $this->container['total_prepaid_amount'];
    }

    /**
     * Sets total_prepaid_amount
     *
     * @param float $total_prepaid_amount total_prepaid_amount
     *
     * @return $this
     */
    public function setTotalPrepaidAmount($total_prepaid_amount)
    {
        $this->container['total_prepaid_amount'] = $total_prepaid_amount;

        return $this;
    }

    /**
     * Gets sender
     *
     * @return \Swagger\Client\Model\IZUGFeRDExportableTradeParty
     */
    public function getSender()
    {
        return $this->container['sender'];
    }

    /**
     * Sets sender
     *
     * @param \Swagger\Client\Model\IZUGFeRDExportableTradeParty $sender sender
     *
     * @return $this
     */
    public function setSender($sender)
    {
        $this->container['sender'] = $sender;

        return $this;
    }

    /**
     * Gets recipient
     *
     * @return \Swagger\Client\Model\IZUGFeRDExportableTradeParty
     */
    public function getRecipient()
    {
        return $this->container['recipient'];
    }

    /**
     * Sets recipient
     *
     * @param \Swagger\Client\Model\IZUGFeRDExportableTradeParty $recipient recipient
     *
     * @return $this
     */
    public function setRecipient($recipient)
    {
        $this->container['recipient'] = $recipient;

        return $this;
    }

    /**
     * Gets delivery_address
     *
     * @return \Swagger\Client\Model\TradeParty
     */
    public function getDeliveryAddress()
    {
        return $this->container['delivery_address'];
    }

    /**
     * Sets delivery_address
     *
     * @param \Swagger\Client\Model\TradeParty $delivery_address delivery_address
     *
     * @return $this
     */
    public function setDeliveryAddress($delivery_address)
    {
        $this->container['delivery_address'] = $delivery_address;

        return $this;
    }

    /**
     * Gets notes
     *
     * @return string[]
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     *
     * @param string[] $notes notes
     *
     * @return $this
     */
    public function setNotes($notes)
    {
        $this->container['notes'] = $notes;

        return $this;
    }

    /**
     * Gets seller_order_referenced_document_id
     *
     * @return string
     */
    public function getSellerOrderReferencedDocumentId()
    {
        return $this->container['seller_order_referenced_document_id'];
    }

    /**
     * Sets seller_order_referenced_document_id
     *
     * @param string $seller_order_referenced_document_id seller_order_referenced_document_id
     *
     * @return $this
     */
    public function setSellerOrderReferencedDocumentId($seller_order_referenced_document_id)
    {
        $this->container['seller_order_referenced_document_id'] = $seller_order_referenced_document_id;

        return $this;
    }

    /**
     * Gets contract_referenced_document
     *
     * @return string
     */
    public function getContractReferencedDocument()
    {
        return $this->container['contract_referenced_document'];
    }

    /**
     * Sets contract_referenced_document
     *
     * @param string $contract_referenced_document contract_referenced_document
     *
     * @return $this
     */
    public function setContractReferencedDocument($contract_referenced_document)
    {
        $this->container['contract_referenced_document'] = $contract_referenced_document;

        return $this;
    }

    /**
     * Gets payment_terms
     *
     * @return \Swagger\Client\Model\IZUGFeRDPaymentTerms
     */
    public function getPaymentTerms()
    {
        return $this->container['payment_terms'];
    }

    /**
     * Sets payment_terms
     *
     * @param \Swagger\Client\Model\IZUGFeRDPaymentTerms $payment_terms payment_terms
     *
     * @return $this
     */
    public function setPaymentTerms($payment_terms)
    {
        $this->container['payment_terms'] = $payment_terms;

        return $this;
    }

    /**
     * Gets invoice_referenced_issue_date
     *
     * @return \DateTime
     */
    public function getInvoiceReferencedIssueDate()
    {
        return $this->container['invoice_referenced_issue_date'];
    }

    /**
     * Sets invoice_referenced_issue_date
     *
     * @param \DateTime $invoice_referenced_issue_date invoice_referenced_issue_date
     *
     * @return $this
     */
    public function setInvoiceReferencedIssueDate($invoice_referenced_issue_date)
    {
        $this->container['invoice_referenced_issue_date'] = $invoice_referenced_issue_date;

        return $this;
    }

    /**
     * Gets specified_procuring_project_id
     *
     * @return string
     */
    public function getSpecifiedProcuringProjectId()
    {
        return $this->container['specified_procuring_project_id'];
    }

    /**
     * Sets specified_procuring_project_id
     *
     * @param string $specified_procuring_project_id specified_procuring_project_id
     *
     * @return $this
     */
    public function setSpecifiedProcuringProjectId($specified_procuring_project_id)
    {
        $this->container['specified_procuring_project_id'] = $specified_procuring_project_id;

        return $this;
    }

    /**
     * Gets specified_procuring_project_name
     *
     * @return string
     */
    public function getSpecifiedProcuringProjectName()
    {
        return $this->container['specified_procuring_project_name'];
    }

    /**
     * Sets specified_procuring_project_name
     *
     * @param string $specified_procuring_project_name specified_procuring_project_name
     *
     * @return $this
     */
    public function setSpecifiedProcuringProjectName($specified_procuring_project_name)
    {
        $this->container['specified_procuring_project_name'] = $specified_procuring_project_name;

        return $this;
    }

    /**
     * Gets despatch_advice_referenced_document_id
     *
     * @return string
     */
    public function getDespatchAdviceReferencedDocumentId()
    {
        return $this->container['despatch_advice_referenced_document_id'];
    }

    /**
     * Sets despatch_advice_referenced_document_id
     *
     * @param string $despatch_advice_referenced_document_id despatch_advice_referenced_document_id
     *
     * @return $this
     */
    public function setDespatchAdviceReferencedDocumentId($despatch_advice_referenced_document_id)
    {
        $this->container['despatch_advice_referenced_document_id'] = $despatch_advice_referenced_document_id;

        return $this;
    }

    /**
     * Gets valid
     *
     * @return bool
     */
    public function getValid()
    {
        return $this->container['valid'];
    }

    /**
     * Sets valid
     *
     * @param bool $valid valid
     *
     * @return $this
     */
    public function setValid($valid)
    {
        $this->container['valid'] = $valid;

        return $this;
    }

    /**
     * Gets zfallowances
     *
     * @return \Swagger\Client\Model\IZUGFeRDAllowanceCharge[]
     */
    public function getZfallowances()
    {
        return $this->container['zfallowances'];
    }

    /**
     * Sets zfallowances
     *
     * @param \Swagger\Client\Model\IZUGFeRDAllowanceCharge[] $zfallowances zfallowances
     *
     * @return $this
     */
    public function setZfallowances($zfallowances)
    {
        $this->container['zfallowances'] = $zfallowances;

        return $this;
    }

    /**
     * Gets zfcharges
     *
     * @return \Swagger\Client\Model\IZUGFeRDAllowanceCharge[]
     */
    public function getZfcharges()
    {
        return $this->container['zfcharges'];
    }

    /**
     * Sets zfcharges
     *
     * @param \Swagger\Client\Model\IZUGFeRDAllowanceCharge[] $zfcharges zfcharges
     *
     * @return $this
     */
    public function setZfcharges($zfcharges)
    {
        $this->container['zfcharges'] = $zfcharges;

        return $this;
    }

    /**
     * Gets zflogistics_service_charges
     *
     * @return \Swagger\Client\Model\IZUGFeRDAllowanceCharge[]
     */
    public function getZflogisticsServiceCharges()
    {
        return $this->container['zflogistics_service_charges'];
    }

    /**
     * Sets zflogistics_service_charges
     *
     * @param \Swagger\Client\Model\IZUGFeRDAllowanceCharge[] $zflogistics_service_charges zflogistics_service_charges
     *
     * @return $this
     */
    public function setZflogisticsServiceCharges($zflogistics_service_charges)
    {
        $this->container['zflogistics_service_charges'] = $zflogistics_service_charges;

        return $this;
    }

    /**
     * Gets zfitems
     *
     * @return \Swagger\Client\Model\IZUGFeRDExportableItem[]
     */
    public function getZfitems()
    {
        return $this->container['zfitems'];
    }

    /**
     * Sets zfitems
     *
     * @param \Swagger\Client\Model\IZUGFeRDExportableItem[] $zfitems zfitems
     *
     * @return $this
     */
    public function setZfitems($zfitems)
    {
        $this->container['zfitems'] = $zfitems;

        return $this;
    }

    /**
     * Gets trade_settlement
     *
     * @return \Swagger\Client\Model\IZUGFeRDTradeSettlement[]
     */
    public function getTradeSettlement()
    {
        return $this->container['trade_settlement'];
    }

    /**
     * Sets trade_settlement
     *
     * @param \Swagger\Client\Model\IZUGFeRDTradeSettlement[] $trade_settlement trade_settlement
     *
     * @return $this
     */
    public function setTradeSettlement($trade_settlement)
    {
        $this->container['trade_settlement'] = $trade_settlement;

        return $this;
    }

    /**
     * Gets own_tax_id
     *
     * @return string
     */
    public function getOwnTaxId()
    {
        return $this->container['own_tax_id'];
    }

    /**
     * Sets own_tax_id
     *
     * @param string $own_tax_id own_tax_id
     *
     * @return $this
     */
    public function setOwnTaxId($own_tax_id)
    {
        $this->container['own_tax_id'] = $own_tax_id;

        return $this;
    }

    /**
     * Gets own_vatid
     *
     * @return string
     */
    public function getOwnVatid()
    {
        return $this->container['own_vatid'];
    }

    /**
     * Sets own_vatid
     *
     * @param string $own_vatid own_vatid
     *
     * @return $this
     */
    public function setOwnVatid($own_vatid)
    {
        $this->container['own_vatid'] = $own_vatid;

        return $this;
    }

    /**
     * Gets own_street
     *
     * @return string
     */
    public function getOwnStreet()
    {
        return $this->container['own_street'];
    }

    /**
     * Sets own_street
     *
     * @param string $own_street own_street
     *
     * @return $this
     */
    public function setOwnStreet($own_street)
    {
        $this->container['own_street'] = $own_street;

        return $this;
    }

    /**
     * Gets own_zip
     *
     * @return string
     */
    public function getOwnZip()
    {
        return $this->container['own_zip'];
    }

    /**
     * Sets own_zip
     *
     * @param string $own_zip own_zip
     *
     * @return $this
     */
    public function setOwnZip($own_zip)
    {
        $this->container['own_zip'] = $own_zip;

        return $this;
    }

    /**
     * Gets own_location
     *
     * @return string
     */
    public function getOwnLocation()
    {
        return $this->container['own_location'];
    }

    /**
     * Sets own_location
     *
     * @param string $own_location own_location
     *
     * @return $this
     */
    public function setOwnLocation($own_location)
    {
        $this->container['own_location'] = $own_location;

        return $this;
    }

    /**
     * Gets own_country
     *
     * @return string
     */
    public function getOwnCountry()
    {
        return $this->container['own_country'];
    }

    /**
     * Sets own_country
     *
     * @param string $own_country own_country
     *
     * @return $this
     */
    public function setOwnCountry($own_country)
    {
        $this->container['own_country'] = $own_country;

        return $this;
    }

    /**
     * Gets detailed_delivery_period_from
     *
     * @return \DateTime
     */
    public function getDetailedDeliveryPeriodFrom()
    {
        return $this->container['detailed_delivery_period_from'];
    }

    /**
     * Sets detailed_delivery_period_from
     *
     * @param \DateTime $detailed_delivery_period_from detailed_delivery_period_from
     *
     * @return $this
     */
    public function setDetailedDeliveryPeriodFrom($detailed_delivery_period_from)
    {
        $this->container['detailed_delivery_period_from'] = $detailed_delivery_period_from;

        return $this;
    }

    /**
     * Gets detailed_delivery_period_to
     *
     * @return \DateTime
     */
    public function getDetailedDeliveryPeriodTo()
    {
        return $this->container['detailed_delivery_period_to'];
    }

    /**
     * Sets detailed_delivery_period_to
     *
     * @param \DateTime $detailed_delivery_period_to detailed_delivery_period_to
     *
     * @return $this
     */
    public function setDetailedDeliveryPeriodTo($detailed_delivery_period_to)
    {
        $this->container['detailed_delivery_period_to'] = $detailed_delivery_period_to;

        return $this;
    }

    /**
     * Gets additional_referenced_documents
     *
     * @return \Swagger\Client\Model\FileAttachment[]
     */
    public function getAdditionalReferencedDocuments()
    {
        return $this->container['additional_referenced_documents'];
    }

    /**
     * Sets additional_referenced_documents
     *
     * @param \Swagger\Client\Model\FileAttachment[] $additional_referenced_documents additional_referenced_documents
     *
     * @return $this
     */
    public function setAdditionalReferencedDocuments($additional_referenced_documents)
    {
        $this->container['additional_referenced_documents'] = $additional_referenced_documents;

        return $this;
    }

    /**
     * Gets correction
     *
     * @return \Swagger\Client\Model\Invoice
     */
    public function getCorrection()
    {
        return $this->container['correction'];
    }

    /**
     * Sets correction
     *
     * @param \Swagger\Client\Model\Invoice $correction correction
     *
     * @return $this
     */
    public function setCorrection($correction)
    {
        $this->container['correction'] = $correction;

        return $this;
    }

    /**
     * Gets own_contact
     *
     * @return \Swagger\Client\Model\Invoice
     */
    public function getOwnContact()
    {
        return $this->container['own_contact'];
    }

    /**
     * Sets own_contact
     *
     * @param \Swagger\Client\Model\Invoice $own_contact own_contact
     *
     * @return $this
     */
    public function setOwnContact($own_contact)
    {
        $this->container['own_contact'] = $own_contact;

        return $this;
    }

    /**
     * Gets subject_note
     *
     * @return string
     */
    public function getSubjectNote()
    {
        return $this->container['subject_note'];
    }

    /**
     * Sets subject_note
     *
     * @param string $subject_note subject_note
     *
     * @return $this
     */
    public function setSubjectNote($subject_note)
    {
        $this->container['subject_note'] = $subject_note;

        return $this;
    }

    /**
     * Gets trade_settlement_payment
     *
     * @return \Swagger\Client\Model\IZUGFeRDTradeSettlementPayment[]
     */
    public function getTradeSettlementPayment()
    {
        return $this->container['trade_settlement_payment'];
    }

    /**
     * Sets trade_settlement_payment
     *
     * @param \Swagger\Client\Model\IZUGFeRDTradeSettlementPayment[] $trade_settlement_payment trade_settlement_payment
     *
     * @return $this
     */
    public function setTradeSettlementPayment($trade_settlement_payment)
    {
        $this->container['trade_settlement_payment'] = $trade_settlement_payment;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
