<?php
/**
 * IZUGFeRDPaymentDiscountTerms
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mustangserver
 *
 * Mustangproject e-invoice REST server API
 *
 * OpenAPI spec version: v0.7.0
 * Contact: jstaerk@usegroup.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.38
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * IZUGFeRDPaymentDiscountTerms Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IZUGFeRDPaymentDiscountTerms implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'IZUGFeRDPaymentDiscountTerms';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'base_period_unit_code' => 'string',
'base_period_measure' => 'int',
'base_date' => '\DateTime',
'calculation_percentage' => 'float'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'base_period_unit_code' => null,
'base_period_measure' => 'int32',
'base_date' => 'date-time',
'calculation_percentage' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'base_period_unit_code' => 'basePeriodUnitCode',
'base_period_measure' => 'basePeriodMeasure',
'base_date' => 'baseDate',
'calculation_percentage' => 'calculationPercentage'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'base_period_unit_code' => 'setBasePeriodUnitCode',
'base_period_measure' => 'setBasePeriodMeasure',
'base_date' => 'setBaseDate',
'calculation_percentage' => 'setCalculationPercentage'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'base_period_unit_code' => 'getBasePeriodUnitCode',
'base_period_measure' => 'getBasePeriodMeasure',
'base_date' => 'getBaseDate',
'calculation_percentage' => 'getCalculationPercentage'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['base_period_unit_code'] = isset($data['base_period_unit_code']) ? $data['base_period_unit_code'] : null;
        $this->container['base_period_measure'] = isset($data['base_period_measure']) ? $data['base_period_measure'] : null;
        $this->container['base_date'] = isset($data['base_date']) ? $data['base_date'] : null;
        $this->container['calculation_percentage'] = isset($data['calculation_percentage']) ? $data['calculation_percentage'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets base_period_unit_code
     *
     * @return string
     */
    public function getBasePeriodUnitCode()
    {
        return $this->container['base_period_unit_code'];
    }

    /**
     * Sets base_period_unit_code
     *
     * @param string $base_period_unit_code base_period_unit_code
     *
     * @return $this
     */
    public function setBasePeriodUnitCode($base_period_unit_code)
    {
        $this->container['base_period_unit_code'] = $base_period_unit_code;

        return $this;
    }

    /**
     * Gets base_period_measure
     *
     * @return int
     */
    public function getBasePeriodMeasure()
    {
        return $this->container['base_period_measure'];
    }

    /**
     * Sets base_period_measure
     *
     * @param int $base_period_measure base_period_measure
     *
     * @return $this
     */
    public function setBasePeriodMeasure($base_period_measure)
    {
        $this->container['base_period_measure'] = $base_period_measure;

        return $this;
    }

    /**
     * Gets base_date
     *
     * @return \DateTime
     */
    public function getBaseDate()
    {
        return $this->container['base_date'];
    }

    /**
     * Sets base_date
     *
     * @param \DateTime $base_date base_date
     *
     * @return $this
     */
    public function setBaseDate($base_date)
    {
        $this->container['base_date'] = $base_date;

        return $this;
    }

    /**
     * Gets calculation_percentage
     *
     * @return float
     */
    public function getCalculationPercentage()
    {
        return $this->container['calculation_percentage'];
    }

    /**
     * Sets calculation_percentage
     *
     * @param float $calculation_percentage calculation_percentage
     *
     * @return $this
     */
    public function setCalculationPercentage($calculation_percentage)
    {
        $this->container['calculation_percentage'] = $calculation_percentage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange] 
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange] 
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange] 
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
