<?php
/**
 * InvoiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mustangserver
 *
 * Mustangproject e-invoice REST server API
 *
 * OpenAPI spec version: v0.7.0
 * Contact: jstaerk@usegroup.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.38
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InvoiceTest Class Doc Comment
 *
 * @category    Class
 * @description Invoice
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Invoice"
     */
    public function testInvoice()
    {
    }

    /**
     * Test attribute "document_name"
     */
    public function testPropertyDocumentName()
    {
    }

    /**
     * Test attribute "document_code"
     */
    public function testPropertyDocumentCode()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "own_organisation_full_plaintext_info"
     */
    public function testPropertyOwnOrganisationFullPlaintextInfo()
    {
    }

    /**
     * Test attribute "reference_number"
     */
    public function testPropertyReferenceNumber()
    {
    }

    /**
     * Test attribute "ship_to_organisation_id"
     */
    public function testPropertyShipToOrganisationId()
    {
    }

    /**
     * Test attribute "ship_to_organisation_name"
     */
    public function testPropertyShipToOrganisationName()
    {
    }

    /**
     * Test attribute "ship_to_street"
     */
    public function testPropertyShipToStreet()
    {
    }

    /**
     * Test attribute "ship_to_zip"
     */
    public function testPropertyShipToZip()
    {
    }

    /**
     * Test attribute "ship_to_location"
     */
    public function testPropertyShipToLocation()
    {
    }

    /**
     * Test attribute "ship_to_country"
     */
    public function testPropertyShipToCountry()
    {
    }

    /**
     * Test attribute "buyer_order_referenced_document_id"
     */
    public function testPropertyBuyerOrderReferencedDocumentId()
    {
    }

    /**
     * Test attribute "invoice_referenced_document_id"
     */
    public function testPropertyInvoiceReferencedDocumentId()
    {
    }

    /**
     * Test attribute "buyer_order_referenced_document_issue_date_time"
     */
    public function testPropertyBuyerOrderReferencedDocumentIssueDateTime()
    {
    }

    /**
     * Test attribute "own_foreign_organisation_id"
     */
    public function testPropertyOwnForeignOrganisationId()
    {
    }

    /**
     * Test attribute "own_organisation_name"
     */
    public function testPropertyOwnOrganisationName()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "payment_term_description"
     */
    public function testPropertyPaymentTermDescription()
    {
    }

    /**
     * Test attribute "issue_date"
     */
    public function testPropertyIssueDate()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "delivery_date"
     */
    public function testPropertyDeliveryDate()
    {
    }

    /**
     * Test attribute "total_prepaid_amount"
     */
    public function testPropertyTotalPrepaidAmount()
    {
    }

    /**
     * Test attribute "sender"
     */
    public function testPropertySender()
    {
    }

    /**
     * Test attribute "recipient"
     */
    public function testPropertyRecipient()
    {
    }

    /**
     * Test attribute "delivery_address"
     */
    public function testPropertyDeliveryAddress()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "seller_order_referenced_document_id"
     */
    public function testPropertySellerOrderReferencedDocumentId()
    {
    }

    /**
     * Test attribute "contract_referenced_document"
     */
    public function testPropertyContractReferencedDocument()
    {
    }

    /**
     * Test attribute "payment_terms"
     */
    public function testPropertyPaymentTerms()
    {
    }

    /**
     * Test attribute "invoice_referenced_issue_date"
     */
    public function testPropertyInvoiceReferencedIssueDate()
    {
    }

    /**
     * Test attribute "specified_procuring_project_id"
     */
    public function testPropertySpecifiedProcuringProjectId()
    {
    }

    /**
     * Test attribute "specified_procuring_project_name"
     */
    public function testPropertySpecifiedProcuringProjectName()
    {
    }

    /**
     * Test attribute "despatch_advice_referenced_document_id"
     */
    public function testPropertyDespatchAdviceReferencedDocumentId()
    {
    }

    /**
     * Test attribute "valid"
     */
    public function testPropertyValid()
    {
    }

    /**
     * Test attribute "zfallowances"
     */
    public function testPropertyZfallowances()
    {
    }

    /**
     * Test attribute "zfcharges"
     */
    public function testPropertyZfcharges()
    {
    }

    /**
     * Test attribute "zflogistics_service_charges"
     */
    public function testPropertyZflogisticsServiceCharges()
    {
    }

    /**
     * Test attribute "zfitems"
     */
    public function testPropertyZfitems()
    {
    }

    /**
     * Test attribute "trade_settlement"
     */
    public function testPropertyTradeSettlement()
    {
    }

    /**
     * Test attribute "own_tax_id"
     */
    public function testPropertyOwnTaxId()
    {
    }

    /**
     * Test attribute "own_vatid"
     */
    public function testPropertyOwnVatid()
    {
    }

    /**
     * Test attribute "own_street"
     */
    public function testPropertyOwnStreet()
    {
    }

    /**
     * Test attribute "own_zip"
     */
    public function testPropertyOwnZip()
    {
    }

    /**
     * Test attribute "own_location"
     */
    public function testPropertyOwnLocation()
    {
    }

    /**
     * Test attribute "own_country"
     */
    public function testPropertyOwnCountry()
    {
    }

    /**
     * Test attribute "detailed_delivery_period_from"
     */
    public function testPropertyDetailedDeliveryPeriodFrom()
    {
    }

    /**
     * Test attribute "detailed_delivery_period_to"
     */
    public function testPropertyDetailedDeliveryPeriodTo()
    {
    }

    /**
     * Test attribute "additional_referenced_documents"
     */
    public function testPropertyAdditionalReferencedDocuments()
    {
    }

    /**
     * Test attribute "correction"
     */
    public function testPropertyCorrection()
    {
    }

    /**
     * Test attribute "own_contact"
     */
    public function testPropertyOwnContact()
    {
    }

    /**
     * Test attribute "subject_note"
     */
    public function testPropertySubjectNote()
    {
    }

    /**
     * Test attribute "trade_settlement_payment"
     */
    public function testPropertyTradeSettlementPayment()
    {
    }
}
