<?php
/**
 * IReferencedDocumentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mustangserver
 *
 * Mustangproject e-invoice REST server API
 *
 * OpenAPI spec version: v0.7.0
 * Contact: jstaerk@usegroup.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.38
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IReferencedDocumentTest Class Doc Comment
 *
 * @category    Class
 * @description IReferencedDocument
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IReferencedDocumentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IReferencedDocument"
     */
    public function testIReferencedDocument()
    {
    }

    /**
     * Test attribute "type_code"
     */
    public function testPropertyTypeCode()
    {
    }

    /**
     * Test attribute "issuer_assigned_id"
     */
    public function testPropertyIssuerAssignedId()
    {
    }

    /**
     * Test attribute "reference_type_code"
     */
    public function testPropertyReferenceTypeCode()
    {
    }
}
