<?php
/**
 * IZUGFeRDExportableProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mustangserver
 *
 * Mustangproject e-invoice REST server API
 *
 * OpenAPI spec version: v0.7.0
 * Contact: jstaerk@usegroup.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.38
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IZUGFeRDExportableProductTest Class Doc Comment
 *
 * @category    Class
 * @description IZUGFeRDExportableProduct
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IZUGFeRDExportableProductTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IZUGFeRDExportableProduct"
     */
    public function testIZUGFeRDExportableProduct()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "global_id"
     */
    public function testPropertyGlobalId()
    {
    }

    /**
     * Test attribute "global_id_scheme"
     */
    public function testPropertyGlobalIdScheme()
    {
    }

    /**
     * Test attribute "reverse_charge"
     */
    public function testPropertyReverseCharge()
    {
    }

    /**
     * Test attribute "intra_community_supply"
     */
    public function testPropertyIntraCommunitySupply()
    {
    }

    /**
     * Test attribute "vatpercent"
     */
    public function testPropertyVatpercent()
    {
    }

    /**
     * Test attribute "seller_assigned_id"
     */
    public function testPropertySellerAssignedId()
    {
    }

    /**
     * Test attribute "buyer_assigned_id"
     */
    public function testPropertyBuyerAssignedId()
    {
    }

    /**
     * Test attribute "tax_category_code"
     */
    public function testPropertyTaxCategoryCode()
    {
    }

    /**
     * Test attribute "tax_exemption_reason"
     */
    public function testPropertyTaxExemptionReason()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "unit"
     */
    public function testPropertyUnit()
    {
    }
}
