<?php
/**
 * IZUGFeRDPaymentDiscountTermsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mustangserver
 *
 * Mustangproject e-invoice REST server API
 *
 * OpenAPI spec version: v0.7.0
 * Contact: jstaerk@usegroup.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.38
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IZUGFeRDPaymentDiscountTermsTest Class Doc Comment
 *
 * @category    Class
 * @description IZUGFeRDPaymentDiscountTerms
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IZUGFeRDPaymentDiscountTermsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IZUGFeRDPaymentDiscountTerms"
     */
    public function testIZUGFeRDPaymentDiscountTerms()
    {
    }

    /**
     * Test attribute "base_period_unit_code"
     */
    public function testPropertyBasePeriodUnitCode()
    {
    }

    /**
     * Test attribute "base_period_measure"
     */
    public function testPropertyBasePeriodMeasure()
    {
    }

    /**
     * Test attribute "base_date"
     */
    public function testPropertyBaseDate()
    {
    }

    /**
     * Test attribute "calculation_percentage"
     */
    public function testPropertyCalculationPercentage()
    {
    }
}
