<?php
/**
 * IZUGFeRDTradeSettlementTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mustangserver
 *
 * Mustangproject e-invoice REST server API
 *
 * OpenAPI spec version: v0.7.0
 * Contact: jstaerk@usegroup.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.38
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IZUGFeRDTradeSettlementTest Class Doc Comment
 *
 * @category    Class
 * @description IZUGFeRDTradeSettlement
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IZUGFeRDTradeSettlementTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IZUGFeRDTradeSettlement"
     */
    public function testIZUGFeRDTradeSettlement()
    {
    }

    /**
     * Test attribute "settlement_xml"
     */
    public function testPropertySettlementXml()
    {
    }

    /**
     * Test attribute "payment_xml"
     */
    public function testPropertyPaymentXml()
    {
    }
}
