<?php
/**
 * IZUGFeRDExportableItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mustangserver
 *
 * Mustangproject e-invoice REST server API
 *
 * OpenAPI spec version: v0.7.0
 * Contact: jstaerk@usegroup.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.38
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IZUGFeRDExportableItemTest Class Doc Comment
 *
 * @category    Class
 * @description IZUGFeRDExportableItem
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IZUGFeRDExportableItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IZUGFeRDExportableItem"
     */
    public function testIZUGFeRDExportableItem()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "product"
     */
    public function testPropertyProduct()
    {
    }

    /**
     * Test attribute "buyer_order_referenced_document_line_id"
     */
    public function testPropertyBuyerOrderReferencedDocumentLineId()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "item_allowances"
     */
    public function testPropertyItemAllowances()
    {
    }

    /**
     * Test attribute "item_charges"
     */
    public function testPropertyItemCharges()
    {
    }

    /**
     * Test attribute "referenced_documents"
     */
    public function testPropertyReferencedDocuments()
    {
    }

    /**
     * Test attribute "basis_quantity"
     */
    public function testPropertyBasisQuantity()
    {
    }

    /**
     * Test attribute "additional_referenced_document_id"
     */
    public function testPropertyAdditionalReferencedDocumentId()
    {
    }

    /**
     * Test attribute "item_total_allowances"
     */
    public function testPropertyItemTotalAllowances()
    {
    }

    /**
     * Test attribute "detailed_delivery_period_from"
     */
    public function testPropertyDetailedDeliveryPeriodFrom()
    {
    }

    /**
     * Test attribute "detailed_delivery_period_to"
     */
    public function testPropertyDetailedDeliveryPeriodTo()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }
}
