<?php
/**
 * TradePartyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mustangserver
 *
 * Mustangproject e-invoice REST server API
 *
 * OpenAPI spec version: v0.7.0
 * Contact: jstaerk@usegroup.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.38
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TradePartyTest Class Doc Comment
 *
 * @category    Class
 * @description TradeParty
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TradePartyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TradeParty"
     */
    public function testTradeParty()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "tax_id"
     */
    public function testPropertyTaxId()
    {
    }

    /**
     * Test attribute "vat_id"
     */
    public function testPropertyVatId()
    {
    }

    /**
     * Test attribute "additional_address"
     */
    public function testPropertyAdditionalAddress()
    {
    }

    /**
     * Test attribute "bank_details"
     */
    public function testPropertyBankDetails()
    {
    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "vatid"
     */
    public function testPropertyVatid()
    {
    }

    /**
     * Test attribute "global_id"
     */
    public function testPropertyGlobalId()
    {
    }

    /**
     * Test attribute "legal_organisation"
     */
    public function testPropertyLegalOrganisation()
    {
    }

    /**
     * Test attribute "global_id_scheme"
     */
    public function testPropertyGlobalIdScheme()
    {
    }

    /**
     * Test attribute "as_trade_settlement"
     */
    public function testPropertyAsTradeSettlement()
    {
    }
}
