<?php
/**
 * ErrorControllerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mustangserver
 *
 * Mustangproject e-invoice REST server API
 *
 * OpenAPI spec version: v0.7.0
 * Contact: jstaerk@usegroup.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.38
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ErrorControllerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ErrorControllerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for handle
     *
     * .
     *
     */
    public function testHandle()
    {
    }

    /**
     * Test case for handle1
     *
     * .
     *
     */
    public function testHandle1()
    {
    }

    /**
     * Test case for handle2
     *
     * .
     *
     */
    public function testHandle2()
    {
    }

    /**
     * Test case for handle3
     *
     * .
     *
     */
    public function testHandle3()
    {
    }

    /**
     * Test case for handle4
     *
     * .
     *
     */
    public function testHandle4()
    {
    }

    /**
     * Test case for handle5
     *
     * .
     *
     */
    public function testHandle5()
    {
    }

    /**
     * Test case for handle6
     *
     * .
     *
     */
    public function testHandle6()
    {
    }
}
