<?php
/**
 * MustangControllerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mustangserver
 *
 * Mustangproject e-invoice REST server API
 *
 * OpenAPI spec version: v0.7.0
 * Contact: jstaerk@usegroup.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.38
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * MustangControllerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MustangControllerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cii2ubl
     *
     * .
     *
     */
    public function testCii2ubl()
    {
    }

    /**
     * Test case for combineXML
     *
     * .
     *
     */
    public function testCombineXML()
    {
    }

    /**
     * Test case for error
     *
     * .
     *
     */
    public function testError()
    {
    }

    /**
     * Test case for extractFile
     *
     * .
     *
     */
    public function testExtractFile()
    {
    }

    /**
     * Test case for invoice2xml
     *
     * .
     *
     */
    public function testInvoice2xml()
    {
    }

    /**
     * Test case for parse
     *
     * .
     *
     */
    public function testParse()
    {
    }

    /**
     * Test case for pdf
     *
     * .
     *
     */
    public function testPdf()
    {
    }

    /**
     * Test case for phive
     *
     * .
     *
     */
    public function testPhive()
    {
    }

    /**
     * Test case for ping
     *
     * .
     *
     */
    public function testPing()
    {
    }

    /**
     * Test case for validateFile
     *
     * .
     *
     */
    public function testValidateFile()
    {
    }
}
